ABAP Kapitel - Grundstruktur und Files - nächster Versuch
1DSAG/ABAP-Leitfaden pull request #50
Opened 2024-11-02 19:32 UTC by ABAP-Pete25

Anpassung der Headers und Navigation. Leider  habe ich das mit den Pages nicht hinbekommen und hoffe das es diesmal passt

2024-11-02 20:19 UTC, fabianlupa commented
Jetzt sieht es so aus:

![image](https://github.com/user-attachments/assets/fc934734-b69a-4eee-b3ae-0273edb711b8)

Ich nehme an die anderen Seiten sollten auch in der Navigation eingebunden sein?

Ich würde außerdem davon abraten von main im Fork die PR aus aufzumachen sondern wie dokumentiert Feature Branches zu nutzen. Ansonsten sieht es nach dem Squash bei der nächsten PR ähnlich aus wie bei Sven in #49 .

2024-11-02 20:26 UTC, fabianlupa requested changes
@ABAP-Pete25 Habs mal dran geschrieben, wo für die korrekte Navigationseinbettung die Werte geändert müssen. ;)

2024-11-02 20:26 UTC, fabianlupa commented on docs/abap/index.md
> +nav_order: 5
Das hier müsste nav_order 3 bleiben wie vorher, 5 ist bereits das Open Source Kapitel.

2024-11-02 20:26 UTC, fabianlupa commented on docs/abap/restful_abap.md
> +parent: abap
parent müsste hier denke ich nun "Moderne ABAP Entwicklung" sein, damit die Datei korrekt untergeordnet in der Navigation auftaucht.

2024-11-02 20:26 UTC, fabianlupa commented on docs/abap/restful_abap.md
> +nav_order: 5
Die nav_order von Unterseiten ist relativ zur übergeordneten Seite und startet daher wieder bei 1 und müsste hier bei den Unterseiten angepasst werden.

2024-11-02 20:26 UTC, fabianlupa commented on docs/abap/enabling_modern_development.md
> +parent: abap
Same here mit parent

2024-11-02 20:26 UTC, fabianlupa commented on docs/abap/enabling_modern_development.md
> +nav_order: 5
Same here mit nav_order

2024-11-02 20:26 UTC, fabianlupa commented on docs/abap/clean_and_modern_abap.md
> +parent: abap
Same here mit parent

2024-11-02 20:26 UTC, fabianlupa commented on docs/abap/clean_and_modern_abap.md
> +nav_order: 5
Same here mit nav_order

2024-11-02 20:26 UTC, fabianlupa commented on docs/abap/architecture_and_design.md
> +parent: abap
Same here mit parent

2024-11-02 20:26 UTC, fabianlupa commented on docs/abap/architecture_and_design.md
> +nav_order: 5
Same here mit nav_order

2024-11-06 14:00 UTC, ABAP-Pete25 commented
Bitte Pull Request stornieren, Neuer PR #54  angelegt aus feature Branch

2024-11-06 14:00 UTC, closed without merging